### ISSUE TITLE
NPC Interaction

### ISSUE THREAD

**Issue by KaiosKen** [Allen-ISD-Computer-Science/REPO_GamblersAscent_2024#7]
Adds an additional keyboard input reader for the letter E, which when in range of an NPC will cause an interaction. The range has not been decided, so it is up to the assignee and subject to approval from the QA.

**Comment by turner-william** [comment]
since there is functionality for what should occur when an NPC is interacted with all the happens is it prints text to the terminal confirming the functionality of the feature.
